text-aid-too: Rewrite service to keep only one dependency (ws)
Indeed, most of its dependencies are obsolete, and one of them starts
failing with:

    file:///usr/local/bin/node_modules/scandirectory/node_modules/safefs/es6/lib/safefs.js:2
    const fsUtil = require('graceful-fs')
                   ^
    ReferenceError: require is not defined
        at file:///usr/local/bin/node_modules/scandirectory/node_modules/safefs/es6/lib/safefs.js:2:16